-- ============================================================
-- AI Resume Screener — Seed Data
-- Database: resume_screening
-- ============================================================

-- ============================================================
-- STEP 1: ORGANISATIONS  (run this first)
-- ============================================================
INSERT INTO organisation (name, industry, website, created_at, updated_at) VALUES
('TechCorp',    'Software',         'https://techcorp.com',   NOW(), NOW()),
('DataSystems', 'Data & Analytics', 'https://datasystems.io', NOW(), NOW()),
('FinanceHub',  'Fintech',          'https://financehub.com', NOW(), NOW());

SELECT id, name FROM organisation;

-- ============================================================
-- STEP 2: USERS  — register via Postman, NOT via SQL
-- BCrypt hashes must be generated by Spring at runtime.
--
--   POST /api/auth/register  (no token needed)
--
--   { "email": "admin@techcorp.com",        "password": "Admin@123",     "role": "ADMIN",     "organisationId": 1 }
--   { "email": "recruiter@techcorp.com",    "password": "Recruiter@123", "role": "RECRUITER", "organisationId": 1 }
--   { "email": "recruiter@datasystems.io",  "password": "Recruiter@123", "role": "RECRUITER", "organisationId": 2 }
--   { "email": "john.doe@gmail.com",        "password": "Candidate@123", "role": "CANDIDATE" }
--   { "email": "jane.smith@gmail.com",      "password": "Candidate@123", "role": "CANDIDATE" }
--
-- Verify after all 5 registers:
--   SELECT id, email, role, organisation_id FROM users;
--   Expected IDs: admin=1, recruiter1=2, recruiter2=3, john=4, jane=5
-- ============================================================

-- ============================================================
-- STEP 3: JOB POSTINGS  (run after Step 2)
-- ============================================================
INSERT INTO job_postings (organisation_id, title, job_description, job_requirements, employment_type, job_status, location, created_at, updated_at) VALUES

(1, 'Java Backend Developer',
 'We are looking for an experienced Java backend developer to design and build scalable REST APIs using Spring Boot.',
 'Java, Spring Boot, Spring Security, PostgreSQL, REST APIs, JWT, Maven, Git, Docker',
 'FULL_TIME', 'OPEN', 'Remote', NOW(), NOW()),

(1, 'DevOps Engineer',
 'Seeking a DevOps engineer to manage CI/CD pipelines and cloud infrastructure on AWS.',
 'Docker, Kubernetes, AWS, Jenkins, Terraform, Linux, Bash scripting',
 'FULL_TIME', 'OPEN', 'Pune, India', NOW(), NOW()),

(2, 'Python Data Engineer',
 'Looking for a data engineer to build and maintain robust data pipelines with large datasets.',
 'Python, Apache Spark, AWS S3, PostgreSQL, Pandas, Airflow, SQL',
 'FULL_TIME', 'OPEN', 'Bangalore, India', NOW(), NOW()),

(2, 'Machine Learning Engineer',
 'Join our ML team to build and deploy predictive models at scale.',
 'Python, TensorFlow, Scikit-learn, Docker, REST APIs, SQL, Git',
 'CONTRACT', 'OPEN', 'Remote', NOW(), NOW()),

(3, 'React Frontend Developer',
 'We need a React developer to build responsive UIs for our fintech platform.',
 'React, TypeScript, HTML, CSS, REST APIs, Git, Jest',
 'FULL_TIME', 'CLOSED', 'Mumbai, India', NOW(), NOW());

SELECT id, title, job_status, organisation_id FROM job_postings;

-- ============================================================
-- STEP 4: RESUMES  (run after Step 2 — candidate IDs must exist)
-- john.doe user id = 4, jane.smith user id = 5
-- If IDs differ run: SELECT id, email FROM users ORDER BY id;
-- and update candidate_id values below accordingly.
-- ============================================================
INSERT INTO resumes (candidate_id, file_path, extracted_text, created_at, updated_at) VALUES

(4, 'uploads/john_doe_resume.pdf',
 'John Doe | john.doe@gmail.com | +91-9876543210
Summary: Experienced Java backend developer with 3 years of experience building REST APIs using Spring Boot and Spring Security. Strong understanding of JWT authentication, PostgreSQL, and Maven.
Skills: Java, Spring Boot, Spring Security, REST APIs, JWT, PostgreSQL, Maven, Git, Hibernate, JPA
Experience:
  - Software Engineer at StartupX (2022-2024): Built microservices, implemented JWT auth, managed PostgreSQL schemas.
  - Junior Developer at WebAgency (2021-2022): Developed CRUD APIs, integrated third-party REST services.
Education: B.Tech Computer Science, Mumbai University, 2021',
 NOW(), NOW()),

(4, 'uploads/john_doe_resume_v2.pdf',
 'John Doe | john.doe@gmail.com
Summary: Java developer with 1 year of experience. Familiar with Spring Boot basics and REST APIs.
Skills: Java, Spring Boot, REST APIs, MySQL, Git
Experience:
  - Junior Developer at WebAgency (2021-2022): Developed basic CRUD endpoints.
Education: B.Tech Computer Science, Mumbai University, 2021',
 NOW(), NOW()),

(5, 'uploads/jane_smith_resume.pdf',
 'Jane Smith | jane.smith@gmail.com | +91-9123456789
Summary: Data engineer with 4 years of experience in Python pipelines and machine learning.
Skills: Python, Pandas, Apache Spark, TensorFlow, Scikit-learn, SQL, PostgreSQL, AWS S3, Airflow, Docker, Git
Experience:
  - Data Engineer at BigData Co (2022-2025): Built ETL pipelines with Airflow and Spark, managed AWS S3 data lakes.
  - ML Intern at AI Startup (2021-2022): Trained classification models using Scikit-learn and TensorFlow.
Education: M.Tech Data Science, IIT Bombay, 2021',
 NOW(), NOW());

SELECT id, candidate_id, file_path FROM resumes;

-- ============================================================
-- STEP 5: SCREENING RESULTS  (pre-seeded, simulates past AI runs)
-- ============================================================
INSERT INTO screening_results (resume_id, job_posting_id, screening_status, match_score, matched_skills, missing_skills, summary, created_at, updated_at) VALUES

(1, 1, 'COMPLETED', 88,
 'Java, Spring Boot, Spring Security, PostgreSQL, REST APIs, JWT, Maven, Git',
 'Docker',
 'Strong candidate with solid Java backend experience. Covers almost all required skills. Missing only Docker.',
 NOW(), NOW()),

(1, 2, 'COMPLETED', 22,
 'Git',
 'Docker, Kubernetes, AWS, Jenkins, Terraform, Linux, Bash scripting',
 'Candidate has strong Java skills but lacks DevOps tooling. Only Git is shared. Not recommended.',
 NOW(), NOW()),

(2, 1, 'COMPLETED', 55,
 'Java, Spring Boot, REST APIs, Git',
 'Spring Security, PostgreSQL, JWT, Maven, Docker',
 'Foundational Java knowledge but lacks advanced skills. Suitable for junior-level consideration only.',
 NOW(), NOW()),

(3, 3, 'COMPLETED', 95,
 'Python, Apache Spark, PostgreSQL, Pandas, Airflow, SQL, AWS S3, Docker',
 'AWS certifications (nice-to-have)',
 'Excellent candidate. Matches all core data engineering requirements. Highly recommended.',
 NOW(), NOW()),

(3, 4, 'COMPLETED', 80,
 'Python, TensorFlow, Scikit-learn, Docker, SQL, Git',
 'REST APIs (model serving)',
 'Very strong ML background. Slightly limited on model deployment via REST but otherwise excellent.',
 NOW(), NOW()),

(3, 1, 'FAILED', NULL, NULL, NULL, NULL, NOW(), NOW());

-- ============================================================
-- FINAL VERIFY — expected: 3 | 5 | 5 | 3 | 6
-- ============================================================
SELECT 'organisation'      AS table_name, COUNT(*) AS row_count FROM organisation
UNION ALL
SELECT 'users',             COUNT(*) FROM users
UNION ALL
SELECT 'job_postings',      COUNT(*) FROM job_postings
UNION ALL
SELECT 'resumes',           COUNT(*) FROM resumes
UNION ALL
SELECT 'screening_results', COUNT(*) FROM screening_results;
